# Generated by Django 3.2.4 on 2021-06-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published',
            field=models.IntegerField(default=1970),
            preserve_default=False,
        ),
    ]
